// seed-routine.js
// Run with: node seed-routine.js
// Make sure your .env is configured with MONGODB_URI

require('dotenv').config();
const mongoose = require('mongoose');
const RoutineEntry = require('./models/routine');

const preliData = [
    {date: '2026-02-20', specialLabel: 'Orientation', entryType: 'special'},
    {
        date: '2026-02-21',
        subject: 'Mental Ability-1',
        topic: 'ঘড়ি ও সময়',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-02-22',
        subject: 'Mental Ability-2',
        topic: 'দিন তারিখ ও বার নির্ণয়',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-02-23',
        subject: 'Mental Ability-3',
        topic: 'অবস্থান নির্ণয় ও ভাষাগত যৌক্তিক বিচার',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ঘড়ি ও সময়',
    },
    {
        date: '2026-02-24',
        specialLabel: 'No Class',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On দিন তারিখ ও বার নির্ণয়',
    },
    {
        date: '2026-02-25',
        subject: 'Mental Ability-4',
        topic: 'যান্ত্রিক দক্ষতা ও সংখ্যাগত দক্ষতা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic:
            'Daily Exam (Preli) On অবস্থান নির্ণয় ও ভাষাগত যৌক্তিক বিচার',
    },
    {
        date: '2026-02-26',
        subject: 'Mental Ability-5',
        topic: 'ত্রিভুজ ও চতুর্ভুজ গণনা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-02-27',
        specialLabel: 'Mental Ability Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-02-28',
        specialLabel: 'Mental Ability Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-03-01',
        specialLabel: 'Mental Ability Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-03-02',
        subject: 'English Grammar-1',
        topic: 'Anatomy of English Sentence, Gerund, Participle',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-03-03',
        subject: 'Bangla Literature-1',
        topic: 'প্রাচীনযুগ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-03-04',
        subject: 'English Grammar-2',
        topic: 'Identification of Phrase & Clause',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic:
            'Daily Exam (Preli) On Anatomy of English Sentence, Gerund, Participle',
    },
    {
        date: '2026-03-05',
        subject: 'Bangla Literature-2',
        topic: 'মধ্যযুগ-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On প্রাচীনযুগ',
    },
    {
        date: '2026-03-06',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On Identification of Phrase & Clause',
    },
    {
        date: '2026-03-07',
        subject: 'English Grammar-3',
        topic: 'Determiner, Noun & Pronoun',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-03-08',
        subject: 'Bangla Literature-3',
        topic: 'মধ্যযুগ-২',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-03-09',
        subject: 'English Grammar-4',
        topic: 'Number & Gender',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On Determiner, Noun & Pronoun',
    },
    {
        date: '2026-03-10',
        subject: 'Bangla Literature-4',
        topic: 'আধুনিক যুগ-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On মধ্যযুগ-২',
    },
    {
        date: '2026-03-14',
        subject: 'English Grammar-6',
        topic: 'Preposition-1',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-03-15',
        subject: 'Bangla Literature-6',
        topic: 'আধুনিক যুগ-৩',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-04-15',
        specialLabel: 'English Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-04-16',
        specialLabel: 'English Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-04-17',
        specialLabel: 'English Open Book',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-04-18',
        specialLabel: 'English Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-04-27',
        specialLabel: 'Bangla Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-04-28',
        specialLabel: 'Bangla Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-04-29',
        specialLabel: 'Bangla Open Book',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-04-30',
        specialLabel: 'Bangla Literature Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-06-12',
        specialLabel: 'Bangla Grammar Final',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-06-13',
        subject: 'BD Affairs-3',
        topic: 'মোগল আমল',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-06-14',
        subject: 'International Affairs-1',
        topic: 'আন্তর্জাতিক বিষয়াবলি প্রস্তুতি, বিশ্ব রাজনীতি ও অর্থনীতির মৌলিক ধারণা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-06-15',
        subject: 'International Affairs-2',
        topic: 'বৈশ্বিক ইতিহাস-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On মোগল আমল',
    },
    {
        date: '2026-06-16',
        subject: 'BD Affairs-4',
        topic: 'ইংরেজ শাসন-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic:
            'Daily Exam (Preli) On আন্তর্জাতিক বিষয়াবলি প্রস্তুতি, বিশ্ব রাজনীতি ও অর্থনীতির মৌলিক ধারণা',
    },
    {
        date: '2026-06-17',
        subject: 'International Affairs-3',
        topic: 'বৈশ্বিক ইতিহাস-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On বৈশ্বিক ইতিহাস-১',
    },
    {
        date: '2026-06-18',
        subject: 'International Affairs-4',
        topic: 'জাতিসংঘ-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ইংরেজ শাসন-১',
    },
    {
        date: '2026-06-19',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On বৈশ্বিক ইতিহাস-২',
    },
    {
        date: '2026-06-20',
        subject: 'BD Affairs-5',
        topic: 'ইংরেজ শাসন-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On জাতিসংঘ-১',
    },
    {
        date: '2026-06-21',
        subject: 'International Affairs-5',
        topic: 'জাতিসংঘ-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-06-22',
        subject: 'International Affairs-6',
        topic: 'এশিয়া-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ইংরেজ শাসন-২',
    },
    {
        date: '2026-06-23',
        subject: 'BD Affairs-6',
        topic: '১৯৪৭ থেকে ভাষা আন্দোলন',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On জাতিসংঘ-২',
    },
    {
        date: '2026-06-24',
        subject: 'International Affairs-7',
        topic: 'এশিয়া-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On এশিয়া-১',
    },
    {
        date: '2026-06-25',
        subject: 'International Affairs-8',
        topic: 'ইউরোপ ও ওশেনিয়া',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ১৯৪৭ থেকে ভাষা আন্দোলন',
    },
    {
        date: '2026-06-26',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On এশিয়া-২',
    },
    {
        date: '2026-06-27',
        subject: 'BD Affairs-7',
        topic: 'যুক্তফ্রন্ট নির্বাচন থেকে ১৯৬৯',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ইউরোপ ও ওশেনিয়া',
    },
    {
        date: '2026-06-28',
        subject: 'International Affairs-9',
        topic: 'আমেরিকা ও আফ্রিকা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-06-29',
        subject: 'International Affairs-10',
        topic: 'পরিবেশ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On যুক্তফ্রন্ট নির্বাচন থেকে ১৯৬৯',
    },
    {
        date: '2026-06-30',
        subject: 'BD Affairs-8',
        topic: '১৯৭০ সালের নির্বাচন ১৯৭১ সালের ২৬ মার্চ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On আমেরিকা ও আফ্রিকা',
    },
    {
        date: '2026-07-01',
        subject: 'International Affairs-11',
        topic: 'আন্তর্জাতিক নিরাপত্তা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On পরিবেশ',
    },
    {
        date: '2026-07-02',
        subject: 'BD Affairs-9',
        topic: 'মুক্তিযুদ্ধ-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic:
            'Daily Exam (Preli) On ১৯৭০ সালের নির্বাচন ১৯৭১ সালের ২৬ মার্চ',
    },
    {
        date: '2026-07-03',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On আন্তর্জাতিক নিরাপত্তা',
    },
    {
        date: '2026-07-04',
        subject: 'BD Affairs-10',
        topic: 'মুক্তিযুদ্ধ-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On মুক্তিযুদ্ধ-১',
    },
    {
        date: '2026-07-05',
        subject: 'International Affairs-12',
        topic: 'আন্তর্জাতিক ক্ষমতা সম্পর্ক ও কূটনীতি',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-07-06',
        subject: 'International Affairs-13',
        topic: 'আন্তর্জাতিক সংগঠন ও জোট-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On মুক্তিযুদ্ধ-২',
    },
    {
        date: '2026-07-07',
        subject: 'International Affairs-14',
        topic: 'আন্তর্জাতিক সংগঠন ও জোট-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On আন্তর্জাতিক ক্ষমতা সম্পর্ক ও কূটনীতি',
    },
    {
        date: '2026-07-08',
        specialLabel: 'International Affairs Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
        examTopic: 'Daily Exam (Preli) On আন্তর্জাতিক সংগঠন ও জোট-১',
    },
    {
        date: '2026-07-09',
        specialLabel: 'International Affairs Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
        examTopic: 'Daily Exam (Preli) On আন্তর্জাতিক সংগঠন ও জোট-২',
    },
    {
        date: '2026-07-10',
        specialLabel: 'International Affairs Open Book',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-07-11',
        specialLabel: 'International Affairs Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-07-12',
        subject: 'BD Affairs-11',
        topic: '১৯৭২ থেকে ১৯৮৪ শাসনামল',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-07-13',
        subject: 'BD Affairs-12',
        topic: 'সংবিধান-১',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-07-14',
        subject: 'BD Affairs-13',
        topic: 'সংবিধান-২',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On ১৯৭২ থেকে ১৯৮৪ শাসনামল',
    },
    {
        date: '2026-07-15',
        subject: 'BD Affairs-14',
        topic: 'সংবিধান-৩',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On সংবিধান-১',
    },
    {
        date: '2026-07-16',
        subject: 'BD Affairs-15',
        topic: 'বাংলাদেশের সরকার ব্যবস্থা-১',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On সংবিধান-২',
    },
    {
        date: '2026-07-17',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On সংবিধান-৩',
    },
    {
        date: '2026-07-18',
        subject: 'BD Affairs-16',
        topic: 'অর্থনীতি',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On বাংলাদেশের সরকার ব্যবস্থা-১',
    },
    {
        date: '2026-07-19',
        subject: 'BD Affairs-17',
        topic: 'শিল্প বাণিজ্য',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-07-20',
        subject: 'BD Affairs-18',
        topic: 'বাংলাদেশের জনসংখ্যা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On অর্থনীতি',
    },
    {
        date: '2026-07-21',
        subject: 'BD Affairs-19',
        topic: 'বাংলাদেশের কৃষিজ সম্পদ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On শিল্প বাণিজ্য',
    },
    {
        date: '2026-07-22',
        subject: 'BD Affairs-20',
        topic: 'স্বাস্থ্য, চলচ্চিত্র, অর্জন, খেলাধুলা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On বাংলাদেশের জনসংখ্যা',
    },
    {
        date: '2026-07-23',
        specialLabel: 'BD Affairs Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-07-24',
        specialLabel: 'BD Affairs Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-07-25',
        specialLabel: 'BD Affairs Open Book Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-07-26',
        specialLabel: 'BD Affairs Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-07-27',
        subject: 'ICT-1',
        topic: 'Computer Architecture, Hardware',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-07-28',
        subject: 'Science-1',
        topic: 'পদার্থের অবস্থা ও গঠন',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-07-29',
        subject: 'ICT-2',
        topic: 'Memory, Software & OS',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On Computer Architecture, Hardware',
    },
    {
        date: '2026-07-30',
        subject: 'Science-2',
        topic: 'পর্যায় সারণী ও প্রতীক সংকেত যোজনী',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Daily Exam (Preli) On পদার্থের অবস্থা ও গঠন',
    },
    {
        date: '2026-07-31',
        specialLabel: 'সাপ্তাহিক নির্বাচিত কলাম',
        entryType: 'special',
        examTopic: 'Daily Exam (Preli) On Memory, Software & OS',
    },
    {
        date: '2026-08-01',
        subject: 'ICT-3',
        topic: 'Number System',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-02',
        subject: 'Science-3',
        topic: 'ভড়িং কোষ ও জারণ-বিজারণ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-08-03',
        subject: 'ICT-4',
        topic: 'Logic Gate',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-04',
        subject: 'Science-4',
        topic: 'এসিড-ক্ষারক-লবণ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-05',
        subject: 'ICT-5',
        topic: 'Computer Network',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-06',
        subject: 'Science-5',
        topic: 'ধাতু-অধাতু',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-08',
        subject: 'ICT-6',
        topic: 'Internet',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-09',
        subject: 'Science-6',
        topic: 'জৈব রসায়ন ও প্রাতিদিক জীবনে রসায়ন',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-08-10',
        subject: 'ICT-7',
        topic: 'Computer Programming',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-11',
        subject: 'Science-7',
        topic: 'ভৌত বিজ্ঞানের বিকাশ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-12',
        subject: 'ICT-8',
        topic: 'Database Management',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-13',
        subject: 'Science-8',
        topic: 'বলবিদ্যা, মহাকর্ষ ও অভিকর্ষ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-15',
        subject: 'ICT-9',
        topic: 'Data Communication',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-16',
        subject: 'Science-9',
        topic: 'কাজ ক্ষমতা শক্তি ও শব্দ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-08-17',
        subject: 'ICT-10',
        topic: 'Website, Cloud Computing, Malware; Security',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-18',
        subject: 'Science-10',
        topic: 'আলো',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-19',
        subject: 'ICT-11',
        topic: 'Tech Giants, e-commerce, social media',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-20',
        specialLabel: 'ICT Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-08-21',
        specialLabel: 'ICT Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-08-22',
        specialLabel: 'ICT Open Book',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-08-23',
        specialLabel: 'ICT Final',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-08-24',
        subject: 'Science-11',
        topic: 'তড়িৎ, তাপ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-25',
        subject: 'Geography-1',
        topic: 'মানচিত্র, কাল্পনিক রেখা, মহাকাশ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-26',
        subject: 'Science-12',
        topic: 'চুম্বকত্ব, ইলেকট্রনিক্স',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-27',
        subject: 'Geography-2',
        topic: 'বাংলাদেশের অবস্থান, সীমানা, বেসামরিকসাগর, ভৌগলিক ব্র্যান্ডিং, জিআই, বাংলাদেশের সম্পদ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-29',
        subject: 'Science-13',
        topic: 'জীববিজ্ঞান এর ক্রমবিকাশ ও কোষ, কোষ বিভাজন',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-08-30',
        subject: 'Geography-3',
        topic: 'ভু-অভ্যন্তরীণ গঠন, ভূমিরূপ, বাংলাদেশের ভূপ্রকৃতি',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-08-31',
        subject: 'Science-14',
        topic: 'কলা, জিনতত্ত্ব',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-01',
        subject: 'Geography-4',
        topic: 'বনজ সম্পদ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-02',
        subject: 'Science-15',
        topic: 'অনুজীব বিজ্ঞান, উদ্ভিদ বিজ্ঞান ও প্রাণিবিচিত্রা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-03',
        subject: 'Geography-5',
        topic: 'বায়ুমণ্ডল',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-05',
        subject: 'Science-16',
        topic: 'মানবদেহ-১',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-06',
        subject: 'Geography-6',
        topic: 'বারিমণ্ডল',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-09-07',
        subject: 'Science-17',
        topic: 'মানবদেহ-২',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-08',
        subject: 'Geography-7',
        topic: 'বাংলাদেশ ও বৈশ্বিক পরিবেশ পরিবর্তন',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-09',
        subject: 'Science-18',
        topic: 'খাদ্য ও পুষ্টি',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-10',
        subject: 'Geography-8',
        topic: 'প্রাকৃতিক দুর্যোগ ও ব্যবস্থাপনা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-11',
        subject: 'Science-19',
        topic: 'দৈনন্দিন জীবনে পদার্থবিজ্ঞান, শক্তির উৎস ও ব্যবহার',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-12',
        specialLabel: 'Geography Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
        examTopic: 'Weekly Mega Exam',
    },
    {
        date: '2026-09-13',
        specialLabel: 'Geography Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-09-14',
        specialLabel: 'Geography Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-09-15',
        specialLabel: 'Science Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-09-16',
        specialLabel: 'Science Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-09-17',
        specialLabel: 'Science Open Book Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-09-18',
        specialLabel: 'Science Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-09-19',
        subject: 'Morality-1',
        topic: 'নৈতিকতা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-20',
        subject: 'Morality-2',
        topic: 'মূল্যবোধ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-21',
        subject: 'Morality-3',
        topic: 'সুশাসন',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-22',
        subject: 'Morality-4',
        topic: 'Extra Class',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-23',
        specialLabel: 'Morality Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-09-24',
        specialLabel: 'Morality Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-09-25',
        specialLabel: 'Morality Open Book',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-09-26',
        specialLabel: 'Morality Final',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-09-27',
        subject: 'Math-1',
        topic: 'বাস্তব ও জটিল সংখ্যা-০১',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-28',
        subject: 'Math-2',
        topic: 'বাস্তব ও জটিল সংখ্যা-০২',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-29',
        subject: 'Math-3',
        topic: 'বীজগাণিতিক রাশি',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-09-30',
        subject: 'Math-4',
        topic: 'সূচক',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-01',
        subject: 'Math-5',
        topic: 'লগ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-03',
        subject: 'Math-6',
        topic: 'সেট ও ফাংশন',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-04',
        subject: 'Math-7',
        topic: 'ধারা',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-10-05',
        subject: 'Math-8',
        topic: 'সরল সহসমীকরণ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-06',
        subject: 'Math-9',
        topic: 'বহুপদী ও দ্বিঘাত সমীকরণ',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-07',
        subject: 'Math-10',
        topic: 'অসমতা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-08',
        subject: 'Math-11',
        topic: 'বিন্যাস ও সমাবেশ বেসিক',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-10',
        subject: 'Math-12',
        topic: 'বিন্যাস',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-11',
        subject: 'Math-13',
        topic: 'সমাবেশ',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-10-12',
        subject: 'Math-14',
        topic: 'সম্ভাবতা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-13',
        specialLabel: 'Algebra Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-10-14',
        specialLabel: 'Algebra Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-10-15',
        specialLabel: 'Algebra Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-10-16',
        specialLabel: 'Algebra Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-10-17',
        subject: 'Math-15',
        topic: 'ত্রিভুজ ও চতুর্ভুজ সংক্রান্ত উপপাদ্য',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-18',
        subject: 'Math-16',
        topic: 'বৃত্ত ও স্থানাংক জ্যামিতি',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-19',
        subject: 'Math-17',
        topic: 'পরিমিতি (ত্রিভুজ সংক্রান্ত)',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-20',
        specialLabel: 'Vijaya Dashami',
        entryType: 'holiday',
        colorTag: 'teal',
    },
    {
        date: '2026-10-21',
        specialLabel: 'Vijaya Dashami',
        entryType: 'holiday',
        colorTag: 'teal',
    },
    {
        date: '2026-10-22',
        subject: 'Math-18',
        topic: 'পরিমিতি (চতুর্ভুজ সংক্রান্ত)',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-24',
        subject: 'Math-19',
        topic: 'পরিমিতি (ঘনবস্তু সংক্রান্ত)',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-25',
        subject: 'Math-20',
        topic: 'ত্রিকোণমিতি',
        entryType: 'class',
        classTime: '9:00 PM',
        examTopic: 'Weekly Mega Exam',
        colorTag: 'teal',
    },
    {
        date: '2026-10-26',
        subject: 'Math-21',
        topic: 'শতকরা ও ভেনচিত্র',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-27',
        subject: 'Math-22',
        topic: 'লাভ-ক্ষতি',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-28',
        subject: 'Math-23',
        topic: 'মুনাফা',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-29',
        subject: 'Math-24',
        topic: 'লসাগু-গসাগু',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-30',
        subject: 'Math-25',
        topic: 'অনুপাত-সমানুপাত',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-10-31',
        subject: 'Math-26',
        topic: 'ঐকিক নিয়ম',
        entryType: 'class',
        classTime: '9:00 PM',
    },
    {
        date: '2026-11-01',
        specialLabel: 'Math Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-11-02',
        specialLabel: 'Math Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-11-03',
        specialLabel: 'Math Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'teal',
    },
    {
        date: '2026-11-04',
        specialLabel: 'P2A Math Olympiad',
        entryType: 'exam',
        colorTag: 'yellow',
    },
    {
        date: '2026-11-05',
        specialLabel: 'Math Final Exam',
        entryType: 'exam',
        colorTag: 'yellow',
    },
];

const writtenData = [
    {
        date: '2026-02-27',
        subject: 'Written Mental Ability-1',
        topic: 'ঘড়ি ও সময়',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-01',
        subject: 'Written Mental Ability-2',
        topic: 'দিন তারিখ ও বার নির্ণয়',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-03',
        subject: 'Written Mental Ability-3',
        topic: 'অবস্থান নির্ণয় ও ভাষাগত যৌক্তিক বিচার',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-05',
        subject: 'Written Mental Ability-4',
        topic: 'যান্ত্রিক দক্ষতা ও সংখ্যাগত দক্ষতা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-05',
        specialLabel: 'Mental Ability Weekly Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-03-07',
        subject: 'Written Mental Ability-5',
        topic: 'ত্রিভুজ ও চতুর্ভুজ গণনা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-08',
        specialLabel: 'Mental Ability Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-03-09',
        specialLabel: 'Mental Ability Self Study & Q Solve',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-03-10',
        specialLabel: 'Mental Ability Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-03-12',
        subject: 'English Freehand Writing-1',
        topic: 'Interchange of Parts Speech',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-13',
        subject: 'Bangla Literature-1 (P-I)',
        topic: 'প্রাচীন যুগ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-15',
        subject: 'English Freehand Writing-2',
        topic: 'Elements of Sentences & Basic Sentence Patterns',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-03-18',
        specialLabel: 'EID VACATION',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-03-19',
        specialLabel: 'EID VACATION',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-03-20',
        specialLabel: 'EID VACATION',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-03-21',
        specialLabel: 'EID VACATION',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-03-22',
        specialLabel: 'EID VACATION',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-06-13',
        specialLabel: 'Bangla Writing Final Exam-2 (002)',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-06-14',
        subject: 'English Freehand Writing-18',
        topic: 'Essay Writing',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-06-15',
        subject: 'English Freehand Writing-19',
        topic: 'Capitalization & Punctuation',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-06-16',
        subject: 'English Freehand Writing-20',
        topic: 'Joining Sentence/Connectors',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-06-18',
        subject: 'English Freehand Writing-21',
        topic: 'Translating Literature',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-06-20',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-21',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-22',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-23',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-24',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-25',
        specialLabel: 'English Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-06-26',
        specialLabel: 'English Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-06-27',
        subject: 'BD Affairs-1',
        topic: 'ভৌগোলিক পরিচিতি-১',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-06-29',
        subject: 'BD Affairs-2',
        topic: 'ভৌগোলিক পরিচিতি-২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-02',
        subject: 'BD Affairs-3',
        topic: 'বাংলাদেশের জনসংখ্যা, ইতিহাস ও সংস্কৃতি-১',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-03',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-07-04',
        subject: 'BD Affairs-4',
        topic: 'বাংলাদেশের জনসংখ্যা, ইতিহাস ও সংস্কৃতি-২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-06',
        subject: 'BD Affairs-5',
        topic: 'বাংলাদেশের অর্থনীতি-১',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-08',
        subject: 'BD Affairs-6',
        topic: 'বাংলাদেশের অর্থনীতি-২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-10',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-07-11',
        subject: 'BD Affairs-7',
        topic: 'বাংলাদেশের অর্থনীতি-৩',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-13',
        subject: 'BD Affairs-8',
        topic: 'বাংলাদেশের পরিবেশ ও প্রকৃতি এবং প্রাকৃতিক সম্পদ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-15',
        subject: 'BD Affairs-9',
        topic: 'বাংলাদেশের সংবিধান-১',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-17',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-07-18',
        subject: 'BD Affairs-10',
        topic: 'বাংলাদেশের সংবিধান-২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-20',
        subject: 'BD Affairs-11',
        topic: 'সরকারের অঙ্গসমূহ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-22',
        subject: 'BD Affairs-12',
        topic: 'বাংলাদেশের পররাষ্ট্রনীতি এবং বিশ্বায়ন ও বাংলাদেশ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-24',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-07-25',
        subject: 'BD Affairs-13',
        topic: 'বাংলাদেশের রাজনৈতিক দলসমূহ ও নির্বাচন ব্যবস্থা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-27',
        subject: 'BD Affairs-14',
        topic: 'তথ্য ও যোগাযোগ প্রযুক্তি, অনানুষ্ঠানিক প্রতিষ্ঠান, সুশীল সমাজ এবং এনজিও',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-29',
        subject: 'BD Affairs-15',
        topic: 'লৈঙ্গিক ইস্যু ও উন্নয়ন',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-07-31',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-08-01',
        subject: 'BD Affairs-16',
        topic: 'মুক্তিযুদ্ধের প্রেক্ষাপট: দেশ ভাগ, ভাষা আন্দোলন, ১৯৫৪-এর নির্বাচন, ১৯৬২-এর শিক্ষা আন্দোলন, ১৯৬৫ এর পাক-ভারত যুদ্ধ পর্যন্ত গুরুত্বপূর্ণ ঘটনাক্রম। ১৯৬৬-র ৬ দফা, ১৯৬৯-এর গণঅভ্যুথান',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-03',
        subject: 'BD Affairs-17',
        topic: '১৯৭০-এর সাধারণ নির্বাচন, ১৯৭১ সালের ২৫ মার্চের গণহত্যা, স্বাধীনতার ঘোষণা, মুজিবনগর সরকার গঠন ও কার্যাবলি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-05',
        subject: 'BD Affairs-18',
        topic: 'মুক্তিযুদ্ধে ভারতসহ পাশ্চাতি ও জাতিসংঘের ভূমিকা, পাকিস্তানি বাহিনীর আত্মসমর্পণ, স্বাধীন বাংলাদেশের অভ্যুদয়',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-07',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-08-08',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-09',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-10',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-11',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-12',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-13',
        specialLabel: 'BD Affairs Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-08-14',
        specialLabel: 'BD Affairs Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-08-15',
        subject: 'International Affairs-1',
        topic: 'Introduction to International Affairs',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-17',
        subject: 'International Affairs-2',
        topic: 'Actors of the world-01',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-19',
        subject: 'International Affairs-3',
        topic: 'Actors of the world-02',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-21',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-08-22',
        subject: 'International Affairs-4',
        topic: 'Actors of the world-03',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-24',
        subject: 'International Affairs-5',
        topic: 'Power & Security-1',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-26',
        subject: 'International Affairs-6',
        topic: 'Power & Security-2',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-28',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-08-29',
        subject: 'International Affairs-7',
        topic: 'Major ideas & ideologies-1',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-08-31',
        subject: 'International Affairs-8',
        topic: 'Major ideas & ideologies-2',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-02',
        subject: 'International Affairs-9',
        topic: 'Foreign Policy & Diplomacy',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-04',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-09-05',
        subject: 'International Affairs-10',
        topic: 'International Economic Relation-01',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-07',
        subject: 'International Affairs-11',
        topic: 'International Economic Relation-02',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-09',
        subject: 'International Affairs-12',
        topic: 'Global Environment',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-11',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-09-12',
        subject: 'International Affairs-13',
        topic: 'Analytical Issues-1',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-14',
        subject: 'International Affairs-14',
        topic: 'Analytical Issues-2',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-16',
        subject: 'International Affairs-15',
        topic: 'Analytical Issues-3',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-18',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-09-19',
        subject: 'International Affairs-16',
        topic: 'Problem Solving-1',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-21',
        subject: 'International Affairs-17',
        topic: 'Problem Solving-2',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-23',
        subject: 'International Affairs-18',
        topic: 'Problem Solving-3',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-09-25',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-09-26',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-09-27',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-09-28',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-09-29',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-09-30',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-10-01',
        specialLabel: 'International Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-10-02',
        specialLabel: 'International Affairs Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-10-03',
        subject: 'Science-1',
        topic: 'আলো',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-05',
        subject: 'Science-2',
        topic: 'শব্দ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-07',
        subject: 'Science-3',
        topic: 'চৌম্বকত্ব',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-09',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-10-10',
        subject: 'Science-4',
        topic: 'অম্ল, ক্ষারক, লবণ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-12',
        subject: 'Science-5',
        topic: 'পানি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-14',
        subject: 'Science-6',
        topic: 'আমাদের সম্পদ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-16',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-10-17',
        subject: 'Science-7',
        topic: 'পলিমার',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-19',
        subject: 'Science-8',
        topic: 'বায়ুমণ্ডল',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-20',
        specialLabel: 'Vijaya Dashami',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-10-21',
        specialLabel: 'Vijaya Dashami',
        entryType: 'holiday',
        colorTag: 'green',
    },
    {
        date: '2026-10-23',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-10-24',
        subject: 'Science-9',
        topic: 'খাদ্য ও পুষ্টি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-26',
        subject: 'Science-10',
        topic: 'জৈব প্রযুক্তি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-28',
        subject: 'Science-11',
        topic: 'রোগ ও স্বাস্থ্য পরিচর্যা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-10-30',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-10-31',
        subject: 'Science-12',
        topic: 'কম্পিউটার প্রযুক্তি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-02',
        subject: 'Science-13',
        topic: 'তথ্য প্রযুক্তি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-04',
        subject: 'Science-14',
        topic: 'ইলেকট্রিক্যাল প্রযুক্তি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-06',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-11-07',
        subject: 'Science-15',
        topic: 'ইলেকট্রনিক্স',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-08',
        specialLabel: 'Science Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-11-09',
        specialLabel: 'Science Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-11-10',
        specialLabel: 'Science Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-11-11',
        specialLabel: 'Science Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-11-12',
        specialLabel: 'Science Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-11-13',
        specialLabel: 'Science Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-11-14',
        subject: 'Written Math-1',
        topic: 'বীজগাণিতিক সূত্রাবলি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-15',
        subject: 'Written Math-2',
        topic: 'বহুপদীর উৎপাদকে বিশ্লেষণ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-16',
        subject: 'Written Math-3',
        topic: 'সূচক',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-17',
        subject: 'Written Math-4',
        topic: 'লগ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-18',
        subject: 'Written Math-5',
        topic: 'সেট, ফাংশন ও ভেনচিত্র',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-19',
        subject: 'Written Math-6',
        topic: 'ধারা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-20',
        specialLabel: 'Written Exam on Previous Topic',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-11-21',
        subject: 'Written Math-7',
        topic: 'অনুপাত-সমানুপাত',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-22',
        subject: 'Written Math-8',
        topic: 'সমীকরণ ও অসমতা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-23',
        subject: 'Written Math-9',
        topic: 'দ্বিপদী-বিস্তৃতি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-24',
        subject: 'Written Math-10',
        topic: 'স্থানাংক জ্যামিতি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-25',
        subject: 'Written Math-11',
        topic: 'বিন্যাস ও সমাবেশ',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-26',
        subject: 'Written Math-12',
        topic: 'সম্ভাব্যতা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-27',
        specialLabel: 'Weekly Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-11-28',
        subject: 'Written Math-13',
        topic: 'জ্যামিতি-০১',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-29',
        subject: 'Written Math-14',
        topic: 'পরিমিতি-০২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-11-30',
        subject: 'Written Math-15',
        topic: 'পরিমিতি-০২',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-01',
        subject: 'Written Math-16',
        topic: 'ত্রিকোণমিতি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-02',
        subject: 'Written Math-17',
        topic: 'শতকরা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-03',
        subject: 'Written Math-18',
        topic: 'লাভ-ক্ষতি',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-04',
        specialLabel: 'Weekly Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-12-05',
        subject: 'Written Math-19',
        topic: 'মুনাফা',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-06',
        subject: 'Written Math-20',
        topic: 'ঐকিক নিয়ম',
        entryType: 'class',
        classTime: '8:00 AM',
    },
    {
        date: '2026-12-11',
        specialLabel: 'Weekly Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
    {
        date: '2026-12-12',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-13',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-14',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-15',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-16',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-17',
        specialLabel: 'Math Self Study',
        entryType: 'self-study',
        colorTag: 'green',
    },
    {
        date: '2026-12-18',
        specialLabel: 'Math Final Exam',
        entryType: 'exam',
        colorTag: 'green',
    },
];

async function seed() {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected');

    await RoutineEntry.deleteMany({batch: 'preli'});
    const preliDocs = preliData.map((e) => ({...e, batch: 'preli'}));
    await RoutineEntry.insertMany(preliDocs);
    console.log(`✅ Preli: ${preliDocs.length} entries seeded`);

    await RoutineEntry.deleteMany({batch: 'written'});
    const writtenDocs = writtenData.map((e) => ({...e, batch: 'written'}));
    await RoutineEntry.insertMany(writtenDocs);
    console.log(`✅ Written: ${writtenDocs.length} entries seeded`);

    await mongoose.disconnect();
    console.log('✅ Done!');
}

seed().catch((err) => {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
});
